
import { httpsCallable, Functions } from "firebase/functions";
import { functions, isFirebaseReady } from "./firebaseConfig";
import { GoogleGenAI, Type, FunctionDeclaration, Tool, FunctionCall } from "@google/genai";
import { AppState, Customer, AgentProfile, Contract, ProductStatus, PlanResult, Appointment, AppointmentStatus, AppointmentType, InteractionType, TimelineItem, IssuanceType } from "../types";
import { addData, updateData, COLLECTIONS } from "./db";

// Initialize Client-side AI (Fallback)
const getApiKey = (): string => {
    const envKey = process.env.API_KEY as string | undefined;
    if (envKey && typeof envKey === 'string' && envKey.length > 0) {
        return envKey;
    }
    return localStorage.getItem('gemini_api_key') || '';
};

const apiKey = getApiKey();
const clientAI = apiKey ? new GoogleGenAI({ apiKey }) : null;

let isServerAvailable = isFirebaseReady;

// MODEL CONFIG
const DEFAULT_MODEL = 'gemini-3-flash-preview'; 

// --- TOOL DEFINITIONS (FUNCTION CALLING) ---

const saveInteractionTool: FunctionDeclaration = {
    name: 'save_interaction',
    description: 'Lưu lịch sử tương tác, ghi chú hoặc kết quả cuộc gọi vào hồ sơ khách hàng.',
    parameters: {
        type: Type.OBJECT,
        properties: {
            customerId: { type: Type.STRING, description: 'ID của khách hàng (lấy từ dữ liệu ngữ cảnh).' },
            content: { type: Type.STRING, description: 'Nội dung chi tiết của tương tác hoặc ghi chú.' },
            type: { type: Type.STRING, description: 'Loại tương tác. Ví dụ: Ghi chú, Cuộc gọi, Gặp mặt, Chat Zalo.' },
            title: { type: Type.STRING, description: 'Tiêu đề ngắn gọn. Ví dụ: Tư vấn sản phẩm A, Khách hỏi về quyền lợi...' }
        },
        required: ['customerId', 'content', 'type', 'title']
    }
};

const createAppointmentTool: FunctionDeclaration = {
    name: 'create_appointment',
    description: 'Tạo lịch hẹn mới hoặc lịch nhắc việc với khách hàng.',
    parameters: {
        type: Type.OBJECT,
        properties: {
            customerId: { type: Type.STRING, description: 'ID của khách hàng.' },
            customerName: { type: Type.STRING, description: 'Tên khách hàng.' },
            date: { type: Type.STRING, description: 'Ngày hẹn định dạng YYYY-MM-DD.' },
            time: { type: Type.STRING, description: 'Giờ hẹn định dạng HH:mm.' },
            type: { type: Type.STRING, description: 'Loại lịch hẹn: Tư vấn, Gọi chăm sóc, Nhắc phí, Chúc mừng sinh nhật, Khác.' },
            note: { type: Type.STRING, description: 'Ghi chú cho lịch hẹn.' }
        },
        required: ['customerId', 'date', 'type']
    }
};

const appTools: Tool[] = [{
    functionDeclarations: [saveInteractionTool, createAppointmentTool]
}];

// --- HELPER TO EXECUTE TOOLS ---
const executeTool = async (functionCall: FunctionCall, appState: AppState): Promise<any> => {
    const { name, args } = functionCall;
    console.log(`🛠️ AI Executing Tool: ${name}`, args);

    try {
        if (name === 'save_interaction') {
            const { customerId, content, type, title } = args as any;
            const customer = appState.customers.find(c => c.id === customerId);
            if (!customer) return { result: "Error: Customer ID not found." };

            const newItem: TimelineItem = {
                id: Date.now().toString(),
                date: new Date().toISOString(),
                type: type as InteractionType || InteractionType.NOTE,
                title: title || 'Ghi chú từ AI',
                content: content,
                result: 'Lưu bởi AI'
            };

            const updatedCustomer = {
                ...customer,
                timeline: [newItem, ...(customer.timeline || [])],
                interactionHistory: [`${new Date().toLocaleDateString()}: ${title} - ${content}`, ...(customer.interactionHistory || [])]
            };

            await updateData(COLLECTIONS.CUSTOMERS, customerId, updatedCustomer);
            return { result: "Success: Đã lưu ghi chú vào hồ sơ khách hàng." };
        }

        if (name === 'create_appointment') {
            const { customerId, customerName, date, time, type, note } = args as any;
            
            const newAppointment: Appointment = {
                id: '', // Generated by Firestore
                customerId,
                customerName: customerName || appState.customers.find(c => c.id === customerId)?.fullName || 'Khách hàng',
                date: date || new Date().toISOString().split('T')[0],
                time: time || '09:00',
                type: type as AppointmentType || AppointmentType.OTHER,
                status: AppointmentStatus.UPCOMING,
                note: note || 'Đặt bởi AI'
            };

            await addData(COLLECTIONS.APPOINTMENTS, newAppointment);
            return { result: `Success: Đã tạo lịch hẹn thành công vào ngày ${date} lúc ${time}.` };
        }

        return { result: `Error: Tool ${name} not supported.` };
    } catch (error: any) {
        console.error("Tool Execution Failed:", error);
        return { result: `Error executing tool: ${error.message}` };
    }
};

// --- HELPER TO EXTRACT PDF TEXT ---
export const extractPdfText = async (url: string): Promise<string> => {
    if (!isServerAvailable || !functions) return "";
    try {
        const gateway = httpsCallable(functions as Functions, 'geminiGateway', { timeout: 300000 }); 
        const result: any = await gateway({
            endpoint: 'extractText',
            url: url
        });
        return result.data.text || "";
    } catch (e) {
        console.error("Failed to extract PDF text:", e);
        return "";
    }
};

// --- MAIN CALL FUNCTION ---
const callAI = async (payload: any): Promise<any> => {
    // 1. Ưu tiên dùng Cloud Function (Server-side)
    if (isServerAvailable && functions) {
        try {
            const gateway = httpsCallable(functions as Functions, 'geminiGateway', { timeout: 300000 }); 
            const result: any = await gateway(payload);
            return result.data; // Returns { text, functionCalls, ... }
        } catch (serverError: any) {
            console.warn("⚠️ Server Backend failed or returned error.", serverError);
            isServerAvailable = false; 
        }
    }

    // 2. Fallback xuống Client-side (Direct API)
    try {
        if (!clientAI) throw new Error("Missing API Key");
        
        const { cachedContent, tools, ...clientPayload } = payload;
        
        const modelId = (clientPayload.model as string) || DEFAULT_MODEL; 
        const config = clientPayload.config || {};
        if (clientPayload.systemInstruction) config.systemInstruction = clientPayload.systemInstruction;
        
        // Pass tools if enabled
        if (tools) config.tools = tools;

        if (clientPayload.endpoint === 'chat') {
            const chat = clientAI.chats.create({
                model: modelId,
                config: config,
                history: clientPayload.history || []
            });
            
            // Handle Message Content (String or Parts)
            const msg = clientPayload.message; 
            const result = await chat.sendMessage({ message: msg });
            
            return {
                text: result.text,
                functionCalls: result.functionCalls
            };
        } else {
            const result = await clientAI.models.generateContent({
                model: modelId,
                contents: clientPayload.contents,
                config: config
            });
            return {
                text: result.text,
                functionCalls: result.functionCalls
            };
        }
    } catch (clientError: any) {
        console.error("❌ Client AI Error:", clientError);
        if (clientError.message.includes("404")) {
             return { text: "Lỗi cấu hình AI (404): Model không tồn tại hoặc API Key không hợp lệ." };
        }
        return { text: `Lỗi AI: ${clientError.message}` };
    }
};

// Helper: Remove Vietnamese accents for better matching
const removeAccents = (str: string) => {
  return str.normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/đ/g, "d").replace(/Đ/g, "D");
};

// --- INTELLIGENT CONTEXT BUILDER ---
const findRelevantContext = (query: string, state: AppState): string => {
    const lowerQuery = query.toLowerCase();
    const noAccentQuery = removeAccents(lowerQuery);
    let context = "";
    
    // --- 1. GLOBAL ROSTER (DANH SÁCH KHÁCH HÀNG HIỆN CÓ) ---
    // Luôn cung cấp danh sách tên để AI biết ai là người thật
    const roster = state.customers.map(c => `- ${c.fullName} (ID: ${c.id})`).join('\n');
    context += `\n=== DANH SÁCH KHÁCH HÀNG THẬT TRONG HỆ THỐNG ===\n(Chỉ trả lời và thực hiện hành động với ID có trong danh sách này)\n${roster}\n==============================================\n`;

    // --- 2. DETECT CUSTOMERS BY NAME / PHONE (DEEP SEARCH) ---
    const matchedCustomers = state.customers.filter(c => {
        const fullName = c.fullName.toLowerCase();
        const noAccentName = removeAccents(fullName);
        const phone = c.phone.replace(/\D/g, ''); 
        
        if (fullName.includes(lowerQuery) || noAccentName.includes(noAccentQuery)) return true;
        if (phone.includes(query) || (query.length >= 4 && phone.endsWith(query))) return true;
        
        const names = fullName.split(' ');
        const firstName = names[names.length - 1];
        if (lowerQuery.length > 2 && lowerQuery.includes(firstName)) return true;
        
        return false;
    });

    if (matchedCustomers.length > 1) {
        context += `\n⚠️ CẢNH BÁO NHẬP NHẰNG: Tìm thấy ${matchedCustomers.length} khách hàng khớp tên.\n`;
        matchedCustomers.forEach(c => {
            context += `- ${c.fullName} (ID: ${c.id}, SĐT: ${c.phone})\n`;
        });
    }

    if (matchedCustomers.length > 0) {
        matchedCustomers.forEach(c => {
            context += `\n--- CHI TIẾT DỮ LIỆU CỦA KHÁCH HÀNG: ${c.fullName} (ID: ${c.id}) ---\n`;
            context += `   - ID: ${c.id}\n`;
            context += `   - Năm sinh: ${new Date(c.dob).getFullYear()}, Giới tính: ${c.gender}\n`;
            context += `   - SĐT: ${c.phone}\n`;
            
            // Add Contracts with WARNINGS for Exclusions
            const customerContracts = state.contracts.filter(ct => ct.customerId === c.id);
            if (customerContracts.length > 0) {
                context += `   - Danh sách Hợp đồng:\n`;
                customerContracts.forEach(ct => {
                    let warning = "";
                    if (ct.issuanceType === IssuanceType.CONDITIONAL) {
                        warning = `[⚠️ CẢNH BÁO: HĐ này CÓ ĐIỀU KIỆN. Loại trừ: "${ct.exclusionNote || 'Không rõ'}". Tăng phí: ${ct.loadingFee || 0}đ]`;
                    }
                    context += `     + Số HĐ: ${ct.contractNumber} (${ct.status}) - ${ct.mainProduct.productName}. ${warning}\n`;
                });
            }

            if (c.timeline && c.timeline.length > 0) {
                const sortedTimeline = [...c.timeline].sort((a,b) => new Date(b.date).getTime() - new Date(a.date).getTime());
                context += `   - Lịch sử tương tác gần nhất:\n`;
                sortedTimeline.slice(0, 5).forEach(t => { 
                    context += `     + [${t.date.split('T')[0]}] ${t.title}: ${t.content}\n`;
                });
            }
            context += `--------------------------------------------------\n`;
        });
    }

    return context;
};

const sanitizeHistory = (history: any[]) => {
    const firstUserIndex = history.findIndex(h => h.role === 'user');
    if (firstUserIndex === -1) return [];
    const validHistory = history.slice(firstUserIndex);
    return validHistory.map(h => ({
        role: h.role,
        parts: h.parts || [{ text: h.text }]
    }));
};

// --- CHAT WITH DATA (RAG + TOOLS) ---
export const chatWithData = async (
  query: string, 
  appState: AppState, 
  history: { role: 'user' | 'model'; text: string }[]
): Promise<string> => {
    
    // 1. Context
    const activeProducts = appState.products.filter(p => p.status === ProductStatus.ACTIVE);
    let knowledgeBase = "";
    activeProducts.forEach(p => {
        if (p.extractedContent) knowledgeBase += `\n--- TÀI LIỆU SẢN PHẨM: ${p.name} ---\n${p.extractedContent.substring(0, 15000)}...\n`; 
    });
    const specificContext = findRelevantContext(query, appState);

    // 2. System Prompt
    const systemInstructionText = `Bạn là TuanChom AI, Trợ lý Nghiệp vụ Bảo hiểm Prudential chuyên nghiệp.
    
    QUYỀN HẠN & CÔNG CỤ:
    - Bạn có quyền TRUY CẬP dữ liệu khách hàng (xem context bên dưới).
    - Bạn có quyền GHI LẠI (Lưu) tương tác và TẠO LỊCH HẸN bằng cách gọi hàm (function calling).
    - Nếu người dùng yêu cầu "Lưu lại", "Ghi chú lại", "Tạo lịch hẹn", "Nhắc tôi...", HÃY GỌI HÀM TƯƠNGỨNG ngay lập tức. Đừng chỉ nói suông.
    
    QUY TẮC QUAN TRỌNG VỀ LOẠI TRỪ (EXCLUSIONS):
    - Khi trả lời về quyền lợi chi trả (Claim), BẮT BUỘC phải kiểm tra xem Hợp đồng có ghi chú [CẢNH BÁO: HĐ này CÓ ĐIỀU KIỆN] không.
    - Nếu có Loại trừ, bạn PHẢI cảnh báo người dùng rằng bệnh/rủi ro này có thể không được chi trả do điều khoản loại trừ.
    
    DỮ LIỆU KHÁCH HÀNG & BỐI CẢNH:
    ${specificContext}
    
    KIẾN THỨC SẢN PHẨM:
    ${knowledgeBase}
    
    HƯỚNG DẪN:
    1. Tra cứu thông tin để trả lời câu hỏi.
    2. Nếu cần lưu thông tin, hãy gọi 'save_interaction'.
    3. Nếu cần đặt lịch, hãy gọi 'create_appointment'.
    4. Trả lời ngắn gọn, chuyên nghiệp.
    `;

    const cleanHistory = sanitizeHistory(history);

    try {
        // STEP 1: First Call to AI (Text or Function Call Request)
        const response = await callAI({
            endpoint: 'chat',
            model: DEFAULT_MODEL, 
            message: query,
            history: cleanHistory,
            systemInstruction: systemInstructionText, 
            tools: appTools, // Enable Tools
            config: { temperature: 0.1 } 
        });

        // STEP 2: Check for Tool Calls
        if (response.functionCalls && response.functionCalls.length > 0) {
            // Execute all requested tools
            const toolResults = [];
            for (const fc of response.functionCalls) {
                const output = await executeTool(fc, appState);
                toolResults.push({
                    functionResponse: {
                        name: fc.name,
                        response: output
                    }
                });
            }

            // STEP 3: Send Tool Results back to AI to get final confirmation text
            // Note: In Cloud Functions or simple chat API, we often just make a fresh call with the result info 
            // or construct a proper multi-turn history. For simplicity here, we append tool result to history and ask for summary.
            
            const toolOutputText = JSON.stringify(toolResults);
            
            // Construct a follow-up message pretending to be the system providing tool outputs
            // Since `chats.create` maintains history in the session instance on client, 
            // but here we might be stateless if using Cloud Functions.
            // We will do a recursive call or a second call with updated history.
            
            const secondTurnResponse = await callAI({
                endpoint: 'chat',
                model: DEFAULT_MODEL,
                // Append the tool execution result as a "User" or "System" message for context
                message: `[System]: Tool execution results: ${toolOutputText}. Hãy xác nhận lại với người dùng bằng tiếng Việt.`,
                history: [
                    ...cleanHistory, 
                    { role: 'user', parts: [{ text: query }] }, 
                    { role: 'model', parts: [{ functionCall: response.functionCalls[0] }] } // Simplified history
                ],
                systemInstruction: systemInstructionText,
                config: { temperature: 0.1 }
            });

            return secondTurnResponse.text || "Đã thực hiện yêu cầu.";
        }

        return response.text || "Xin lỗi, tôi không hiểu ý bạn.";

    } catch (error: any) {
        console.error("Chat Error:", error);
        return "Xin lỗi, hệ thống đang gặp sự cố kết nối.";
    }
};

// ... (Rest of existing functions like consultantChat, etc. remain unchanged) ...
export const consultantChat = async (
    query: string, customer: Customer, contracts: Contract[], familyContext: any[],
    agentProfile: AgentProfile | null, conversationGoal: string,
    history: { role: 'user' | 'model'; text: string }[],
    roleplayMode: 'consultant' | 'customer' = 'consultant',
    planResult: PlanResult | null = null,
    chatStyle: 'zalo' | 'formal' = 'formal'
): Promise<string> => {
    
    let agentContext = "Tên bạn: Tư vấn viên Prudential.";
    if (agentProfile) {
        agentContext = `
        THÔNG TIN CỦA BẠN (TƯ VẤN VIÊN):
        - Họ tên: ${agentProfile.fullName}
        - Danh hiệu: ${agentProfile.title}
        - Đơn vị: ${agentProfile.office || "Prudential Vietnam"}
        `;
    }

    const customerContext = `
    THÔNG TIN KHÁCH HÀNG:
    - Họ tên: ${customer.fullName}
    - Tuổi: ${new Date().getFullYear() - new Date(customer.dob).getFullYear()}
    - Nghề nghiệp: ${customer.job}
    - Tình trạng: ${customer.status}
    - Mối quan tâm: ${customer.analysis?.keyConcerns || 'Chưa rõ'}
    - Tính cách (DISC): ${customer.analysis?.personality || 'Chưa rõ'}
    `;

    const contractInfo = contracts.length > 0 
        ? contracts.map(c => {
            let info = `- HĐ ${c.contractNumber}: ${c.mainProduct.productName} (${c.status}). Phí: ${c.totalFee.toLocaleString()}đ`;
            if (c.issuanceType === IssuanceType.CONDITIONAL) {
                info += `\n  ⚠️ LƯU Ý QUAN TRỌNG: HĐ này CÓ ĐIỀU KIỆN. Loại trừ: "${c.exclusionNote}". Tăng phí: ${c.loadingFee}đ.`;
            }
            return info;
        }).join('\n') 
        : "Chưa có hợp đồng nào.";
    
    const familyInfo = familyContext.length > 0
        ? familyContext.map(f => `- ${f.relationship}: ${f.name || 'Người thân'} `).join('\n')
        : "Chưa có thông tin gia đình.";

    let planContext = "";
    if (planResult) {
        planContext = `
        DỮ LIỆU TÀI CHÍNH THỰC TẾ:
        - Mục tiêu: ${planResult.goal}
        - Thiếu hụt (Gap): ${planResult.shortfall.toLocaleString()}đ
        `;
    }

    const systemInstruction = `
    BỐI CẢNH: Bạn đang tham gia Roleplay (Mô phỏng tư vấn).
    VAI TRÒ CỦA BẠN: ${roleplayMode === 'consultant' ? 'TƯ VẤN VIÊN CHUẨN MDRT' : 'KHÁCH HÀNG'}.
    ${roleplayMode === 'consultant' ? agentContext : ''}
    ${customerContext}
    THÔNG TIN BỔ SUNG:
    - Hợp đồng hiện tại (Chú ý các điều khoản loại trừ nếu có): 
    ${contractInfo}
    - Gia đình: ${familyInfo}
    ${planContext}
    MỤC TIÊU: ${conversationGoal}
    PHONG CÁCH: ${chatStyle === 'zalo' ? 'Thân mật, ngắn gọn (Zalo)' : 'Chuyên nghiệp (Email/Gặp)'}.
    
    ${roleplayMode === 'consultant' ? `
    QUY TẮC MDRT:
    1. Không bán hàng gượng ép.
    2. Dẫn dắt bằng câu hỏi.
    3. Tập trung vào "Tại sao" (Why).
    4. Đồng cảm trước khi giải quyết từ chối.
    ` : `
    HƯỚNG DẪN KHÁCH HÀNG:
    1. Đóng vai Khách hàng ${customer.fullName}.
    2. Phản ứng dựa trên tính cách: ${customer.analysis?.personality}.
    `}
    `;

    const cleanHistory = sanitizeHistory(history);

    try {
        const result = await callAI({
            endpoint: 'chat',
            model: DEFAULT_MODEL,
            message: query,
            history: cleanHistory,
            systemInstruction: systemInstruction,
            config: { temperature: 0.7 }
        });
        return result.text;
    } catch (e) {
        return "Lỗi kết nối AI.";
    }
};

export const getObjectionSuggestions = async (msg: string, customer: Customer): Promise<any[]> => {
    const result = await callAI({
        endpoint: 'generateContent',
        model: DEFAULT_MODEL,
        contents: `Khách hàng vừa nói: "${msg}". Đóng vai Coach MDRT, gợi ý 3 cách xử lý từ chối (Đồng cảm, Hỏi ngược, Kể chuyện).`,
        config: { 
            responseMimeType: "application/json",
            responseSchema: {
                type: Type.ARRAY,
                items: {
                    type: Type.OBJECT,
                    properties: {
                        label: { type: Type.STRING },
                        type: { type: Type.STRING },
                        content: { type: Type.STRING }
                    },
                    required: ["label", "type", "content"]
                }
            }
        }
    });
    try { return JSON.parse(result.text); } catch { return []; }
};

export const generateSocialPost = async (topic: string, tone: string): Promise<any[]> => {
    const result = await callAI({
        endpoint: 'generateContent',
        model: DEFAULT_MODEL,
        contents: `Topic: ${topic}. Tone: ${tone}. Viết 3 status FB. Output JSON array {title, content}.`,
        config: { responseMimeType: "application/json" }
    });
    try { return JSON.parse(result.text); } catch { return []; }
};

export const generateContentSeries = async (topic: string): Promise<any[]> => {
    const result = await callAI({
        endpoint: 'generateContent',
        model: DEFAULT_MODEL,
        contents: `Topic: ${topic}. Plan 5 days content series. Output JSON array {day, type, content}.`,
        config: { responseMimeType: "application/json" }
    });
    try { return JSON.parse(result.text); } catch { return []; }
};

export const generateStory = async (facts: string, emotion: string): Promise<string> => {
    const result = await callAI({
        endpoint: 'generateContent',
        model: DEFAULT_MODEL,
        contents: `Facts: ${facts}. Emotion: ${emotion}. Write a touching story.`,
        config: { temperature: 0.9 }
    });
    return result.text;
};

export const generateFinancialAdvice = async (customerName: string, planResult: PlanResult): Promise<string> => {
    const prompt = `Bạn là Chuyên gia Tài chính Prudential. Nhận xét ngắn về KH ${customerName}. Mục tiêu: ${planResult.goal}. Gap: ${planResult.shortfall.toLocaleString()}đ. Lời khuyên 3 câu.`;
    const result = await callAI({ endpoint: 'generateContent', model: DEFAULT_MODEL, contents: prompt });
    return result.text;
};

export const generateClaimSupport = async (contract: Contract, customer: Customer): Promise<string> => {
    const result = await callAI({
        endpoint: 'generateContent',
        model: DEFAULT_MODEL,
        contents: `Soạn tin hướng dẫn Claim HĐ ${contract.contractNumber} cho ${customer.fullName}`
    });
    return result.text;
};
